#!/usr/bin/env python3

# EPG merger (Optimized v1.5 - Fixed Bugs & Faster I/O)
# Original by: @thefirefox12537

import glob
import shutil
import requests
import os
import re
import sys
import lxml.etree as et

# Validasi argumen
if len(sys.argv) < 5:
    print("[ERROR] Missing arguments.")
    sys.exit(1)

exec_name, result, source, caption_name, caption_url = sys.argv
tmpdir = os.path.join("..", "tmp")

def load_mappings(files, source_path):
    """Membaca semua file teks pemetaan sekali saja di awal untuk menghemat I/O"""
    mappings = {}
    source_dir = os.path.dirname(os.path.abspath(source_path))
    
    for file in files:
        base_name = os.path.basename(file)
        name_only, _ = os.path.splitext(base_name)
        epgid_path = os.path.join(source_dir, name_only + ".txt")
        
        mappings[base_name] = {}
        if os.path.exists(epgid_path):
            with open(epgid_path, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or "," not in line:
                        continue
                    old, new = line.split(",", 1)
                    mappings[base_name][old.strip()] = new.strip()
    return mappings

def merge(tree, tagname, attrib, files, mappings):
    print(f"Merging {tagname}...")
    for file in files:
        base_name = os.path.basename(file)
        mapping = mappings.get(base_name, {})
        
        try:
            # Menggunakan iterparse (bukan parse penuh) agar lebih hemat memori
            context = et.iterparse(file, events=("end",), tag=tagname)
            for _, child in context:
                val = child.attrib.get(attrib)
                if val in mapping:
                    child.attrib[attrib] = mapping[val]
                
                # Pindahkan elemen ke tree utama
                tree.append(child)
        except Exception as e:
            print(f"Skipping corrupt file {file}: {e}")

def main():
    files = []
    urls = []

    if os.path.exists(result):
        os.remove(result)
    os.makedirs(tmpdir, exist_ok=True)
    
    if not os.path.exists(source):
        print(f"[ERROR] {source} does not exist")
        sys.exit(1)

    # Perbaikan pembacaan source (Aman untuk berbagai format URL)
    with open(source, mode="r", encoding="utf-8") as epg:
        for line in epg:
            line = line.strip()
            if not line:
                continue
            if line.startswith("http"):
                urls.append(line)
            else:
                files.append(line)

    # Unduh file secara berurutan
    session = requests.Session()
    for url, name in zip(urls, files):
        epgxml = os.path.join(tmpdir, name)
        if not os.path.exists(epgxml):
            try:
                print(f"Downloading {name}...")
                res = session.get(url, timeout=30)
                res.raise_for_status()
                with open(epgxml, mode="wb") as f:
                    f.write(res.content)
            except Exception as e:
                print(f"Failed to download {name}: {e}")

    # Atribut Root XML
    root_attrib = {
        "generator-info-name": f"EPG generated by {caption_name}",
        "generator-info-url": caption_url
    }
    tree = et.Element("tv", root_attrib)
    
    xml_files = glob.glob(os.path.join(tmpdir, "*.xml"))
    
    # Memuat mapping ke memori (Hanya dilakukan 1 kali!)
    mappings = load_mappings(xml_files, source)

    # Eksekusi penggabungan data
    merge(tree, tagname="channel", attrib="id", files=xml_files, mappings=mappings)
    merge(tree, tagname="programme", attrib="channel", files=xml_files, mappings=mappings)

    print("Creating file...")
    # lxml bisa melakukan pretty_print secara native tanpa bantuan xml.dom.minidom
    with open(result, mode="wb") as epg:
        epg.write(et.tostring(tree, encoding="UTF-8", xml_declaration=True, pretty_print=True))

    print("Removing temporary files...")
    shutil.rmtree(tmpdir, ignore_errors=True)
    print("Finished successfully.")

if __name__ == "__main__":
    main()
