#!/usr/bin/env python3
#
# EPG Merger
#

import glob
import os
import re
import shutil
import sys
import requests
import lxml.etree as et
import xml.dom.minidom as dom

if len(sys.argv) != 5:
    print("Usage:")
    print("python index.py output.xml source.txt author website")
    sys.exit(1)

_, result, source, caption_name, caption_url = sys.argv

TMP_DIR = os.path.join("..", "tmp")


def merge(tree, tagname, attrib):
    print(f"Merging {tagname}...")

    for xmlfile in glob.glob(os.path.join(TMP_DIR, "*.xml")):
        try:
            root = et.parse(xmlfile).getroot()

            mapping = os.path.join(
                os.path.dirname(source),
                os.path.basename(xmlfile) + ".txt"
            )

            remap = {}

            if os.path.exists(mapping):
                with open(mapping, encoding="utf-8") as f:
                    for line in f:
                        row = line.strip().split(",", 1)
                        if len(row) == 2:
                            remap[row[0]] = row[1]

            for child in root:
                if tagname not in child.tag:
                    continue

                key = child.attrib.get(attrib)

                if key in remap:
                    child.attrib[attrib] = remap[key]

                tree.append(child)

        except Exception as e:
            print(f"Skipping {xmlfile}: {e}")


def download(urls, names):
    session = requests.Session()

    session.headers.update({
        "User-Agent": "EPG-Generator/1.0"
    })

    for url, name in zip(urls, names):
        outfile = os.path.join(TMP_DIR, name)

        if os.path.exists(outfile):
            continue

        print(f"Downloading {name}")

        try:
            r = session.get(url, timeout=60)
            r.raise_for_status()

            with open(outfile, "wb") as f:
                f.write(r.content)

        except Exception as e:
            print(f"Failed: {url}")
            print(e)


def main():

    if os.path.exists(result):
        os.remove(result)

    os.makedirs(TMP_DIR, exist_ok=True)

    if not os.path.exists(source):
        print(f"{source} not found.")
        sys.exit(1)

    names = []
    urls = []

    with open(source, encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            if line.startswith("http") and line.endswith(".xml"):
                urls.append(line)
            else:
                names.append(line)

    if len(names) != len(urls):
        print("ERROR:")
        print(f"Names : {len(names)}")
        print(f"URLs  : {len(urls)}")
        print("Every filename must have one XML URL.")
        sys.exit(1)

    download(urls, names)

    attrs = {
        "generator-info-name": f"EPG generated by {caption_name}",
        "generator-info-url": caption_url
    }

    tree = et.Element("tv", attrs)

    merge(tree, "channel", "id")
    merge(tree, "programme", "channel")

    print("Writing XML...")

    xml = et.tostring(
        tree,
        encoding="UTF-8",
        xml_declaration=True
    )

    pretty = dom.parseString(xml).toprettyxml(
        indent="",
        encoding="UTF-8"
    )

    pretty = re.sub(b"\n\n+", b"\n", pretty)

    with open(result, "wb") as f:
        f.write(pretty)

    print("Cleaning temporary files...")

    shutil.rmtree(TMP_DIR, ignore_errors=True)

    print("Done.")


if __name__ == "__main__":
    main()
