#!/usr/bin/env python3

import glob
import os
import re
import shutil
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor

import requests
import lxml.etree as et

if len(sys.argv) != 5:
    print("Usage:")
    print("python index.py output.xml source.txt author website")
    sys.exit(1)

_, result, source, caption_name, caption_url = sys.argv

TMPDIR = tempfile.mkdtemp(prefix="epg_")


def load_mapping():
    mapping = {}

    for txt in glob.glob(os.path.join(os.path.dirname(source), "*.txt")):
        data = {}

        with open(txt, encoding="utf-8") as f:
            for line in f:
                row = line.strip().split(",", 1)
                if len(row) == 2:
                    data[row[0]] = row[1]

        mapping[os.path.basename(txt)] = data

    return mapping


def download(session, url, filename):
    outfile = os.path.join(TMPDIR, filename)

    if os.path.exists(outfile):
        return

    print("Downloading", filename)

    r = session.get(
        url,
        timeout=60,
        allow_redirects=True,
        headers={
            "User-Agent": "EPG Generator"
        }
    )

    r.raise_for_status()

    with open(outfile, "wb") as f:
        f.write(r.content)


def merge(tree, tag, attrib, remaps):

    for xmlfile in sorted(glob.glob(os.path.join(TMPDIR, "*.xml"))):

        try:

            root = et.parse(xmlfile).getroot()

            lookup = remaps.get(
                os.path.basename(xmlfile) + ".txt",
                {}
            )

            for child in root:

                if tag not in child.tag:
                    continue

                key = child.attrib.get(attrib)

                if key in lookup:
                    child.attrib[attrib] = lookup[key]

                tree.append(child)

        except Exception as e:
            print("Skipping", xmlfile, e)


def main():

    if os.path.exists(result):
        os.remove(result)

    if not os.path.exists(source):
        print(source, "not found")
        sys.exit(1)

    names = []
    urls = []

    with open(source, encoding="utf-8") as f:

        for line in f:

            line = line.strip()

            if not line:
                continue

            if re.match(r"^https?://.*\.xml$", line):
                urls.append(line)
            else:
                names.append(line)

    if len(names) != len(urls):
        print("Configuration error")
        sys.exit(1)

    session = requests.Session()

    with ThreadPoolExecutor(max_workers=6) as pool:

        futures = []

        for url, name in zip(urls, names):
            futures.append(
                pool.submit(download, session, url, name)
            )

        for f in futures:
            f.result()

    remaps = load_mapping()

    attrs = {
        "generator-info-name":
            f"EPG generated by {caption_name}",
        "generator-info-url":
            caption_url
    }

    tv = et.Element("tv", attrs)

    merge(tv, "channel", "id", remaps)
    merge(tv, "programme", "channel", remaps)

    et.ElementTree(tv).write(
        result,
        encoding="UTF-8",
        xml_declaration=True,
        pretty_print=False
    )

    shutil.rmtree(TMPDIR, ignore_errors=True)

    print("Done")


if __name__ == "__main__":
    main()
