name: Update EPG

on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        job:
          - aio
          - maxstream
          - visionplus
          - vidio
          - cubmu
          - dens        

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout iptv-org/epg
        uses: actions/checkout@v6
        with:
          repository: iptv-org/epg
          path: iptv-org-epg

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: iptv-org-epg/package-lock.json

      - name: Generate EPG
        run: |
          chmod +x epg/scripts/epg-id.sh
          bash epg/scripts/epg-id.sh "${{ matrix.job }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: epg-${{ matrix.job }}
          path: epg/*.gz
          if-no-files-found: ignore

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: Copy Files
        run: |
          mkdir -p epg
          find artifacts -name "*.gz" -exec cp {} epg/ \;

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & Push
        run: |
          git add epg/
          git commit -m "Update EPG"
          git push origin main
