name: Update EPG

on:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout iptv-org/epg
        uses: actions/checkout@v4
        with:
          repository: iptv-org/epg
          path: iptv-org-epg

      - name: Update EPG
        run: bash epg/scripts/epg-id.sh

      - name: Configure Git
        run: |
          git config user.name "Rejopa"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add epg/files/
          git commit -m "Update EPG"
          git push origin main
