name: Generate EPG every day
on:
  schedule:
    - cron: '00 00-12/6 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: config
        run: |
          git pull
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: generate
        run: |
          cd epg
          pwd       
          python3 -m pip install lxml
          python scripts/index.py guide.xml scripts/main/main.txt "action@github.com" "GitHub Action"
          python scripts/index.py local.xml scripts/local/local.txt "action@github.com" "GitHub Action"
          python scripts/index.py nze.xml scripts/nze/nze.txt "action@github.com" "GitHub Action"

      - name: Compress XML
        working-directory: epg
        run: |
          gzip -9 -f guide.xml &
          gzip -9 -f local.xml &
          gzip -9 -f nze.xml &
          wait

      - name: Commit Changes
        run: |
          git add -A

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "SIP Auto Update EPG"
          git push
