name: pipa

on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
   build:  
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: config
        run: |
          git pull
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Update list
        run: |
          pwd
          python3 cepuk/semprong.py "https://www.youtube.com/@aljazeera/live" > seeme/aljaar.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/@aljazeeraenglish/live" > seeme/aljaen.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/channel/UCcZg5r9hBqK_VPUT2I7eYVw/live" > seeme/bernama.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/c/ABCNews/live" > seeme/ABCNews.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/channelnewsasia/live" > seeme/cna.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/c/HopeChannelIndonesia/live" > seeme/hope.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/watch?v=w7ZTt55F5YE" > seeme/kompi.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/@kompastv/live" > seeme/kompil.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/c/MetrotvnewsOfficial/live" > seeme/mevi.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/c/tvonenews/live" > seeme/viwan.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/@NetInsights/live" > seeme/nevi.m3u8
          sleep 3
          python3 cepuk/semprong.py "https://www.youtube.com/@Reformed21TV/live" > seeme/r21.m3u8
          sleep 3
         
      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "yt OK"
          git push
