name: Update Pijar TV

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-pijartv
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: glow
        run: npm install

      - name: Generate Pijar TV playlist
        working-directory: glow
        run: node index.js

      - name: Show generated playlist
        run: |
          echo "=== glow/pijartv.m3u ==="
          cat glow/pijartv.m3u

      - name: Commit updated playlist
        run: |
          git config user.name "robo-robo[bot]"
          git config user.email "Rejopa@users.noreply.github.com"

          git add glow/pijartv.m3u

          if git diff --cached --quiet; then
            echo "Tidak ada perubahan."
            exit 0
          fi

          git commit -m "Update Pijar TV stream"
          git push
